name: CI

# Run this wts pushed to main or a pusll request gets openedss againt mbabs
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/devlps/GitAct
            azure-pipeline-name: 'My Pipeline'
            azure-devops-token: ${{ secrets.AZURE_TOKEN }}
